### ISSUE TITLE
Open source Icinga2 setup documentation

### ISSUE THREAD

**Issue by joschi36** [vshn/signalilo#15]
I'm currently working to get Signalilo working.

But i need to know how to configure Icinga 2 Hosts and Services. But there is only a link to your internal wiki.
https://wiki.vshn.net/display/VT/Icinga2+passive+checks

I will try now with this presentation: https://www.slideshare.net/icinga/signalilo-visualizing-prometheus-alerts-in-icinga2-icinga-camp-zurich-2019

**Comment by simu** [comment]
Hey Joshua,

Thanks for the feedback, we will update the public documentation soon. The presentation does reflect the setup we're using internally, slides 9 - 11 detail everything you need to setup by hand in Icinga2. Signalilo will then create new services for incoming alerts on the Icinga2 host.

**Comment by tectumopticum** [comment]
> Thanks for the feedback, we will update the public documentation soon. The presentation does reflect the setup we're using internally, slides 9 - 11 detail everything you need to setup by hand in Icinga2. Signalilo will then create new services for incoming alerts on the Icinga2 host.

Hi Simon,
I'm trying to achieve this service template config by using Icinga-Director. It would be nice if an update of the public documentation will also cover this.

**Comment by mahauke** [comment]
I'm also interested in a more detailled documentation of the Icinga passive check than the one provided in the slides.
Is this in your private WIKI under https://wiki.vshn.net/display/VT/Icinga2+passive+checks ?

I would be happy to see something public here.

**Comment by simu** [comment]
Hi, I've updated the README with the service host and heartbeat service configs that we're currently use.

@tectumopticum I don't have any experience with Icinga-Director, so I hope you can adjust the provided configs for use with Icinga-Director.

**Comment by mahauke** [comment]
Hi Simon. Perfect - thank you!
