### ISSUE TITLE
Consistent ProcessCheckResult failures with icinga 2.8.4

### ISSUE THREAD

**Issue by mc-meta** [vshn/signalilo#29]
Hello,

we have experienced consistent failures in signalilo during ProcessCheckResult such as the one below:
 
```
{"level":"error","msg":"Error in ProcessCheckResult for Watchdog_53f82e5f93b8c355: Post \"https://icinga-stg.xxxx.io:5665/v1/actions/process-check-result\": EOF","time":"2020-06-16T21:06:45Z"}
```

We've been able to replicate exact failure by instantiating some Go icinga2 client transactions. Similar failures are not happening when simulating via curl or an icinga python client. 

Failure seems to be related to Go http client not playing well with icinga2 api module in our environment (icinga 2.8.4 with some customizations on a CentOS 7.5) and are likely related to timeout issues .

We have been able to workaround this problem by disabling http keepalive.

We are going to propose a couple of pull requests so that http keepalive could be tuned in signalilo and pushed down to Go icinga2 client.

We are available in case you are interested in looking further into this problem.

HTH,

-m

**Comment by mc-meta** [comment]
PRs added:

https://github.com/vshn/go-icinga2-client/pull/1
https://github.com/vshn/signalilo/pull/30

**Comment by simu** [comment]
Hi @mc-meta ,

Can you confirm that the PRs linked in this issue have resolved your problem?

**Comment by mc-meta** [comment]
Hello @simu ,

PRs do indeed solve my problem and i'm using a custom image since few months without issues.  I was waiting for a new official release to actually do an e2e test and reference that in closing message, but if you prefer we may progress with closure now.

**Comment by simu** [comment]
Ok, thanks for the feedback.

I'm planning to do a new release this week, and was going over the open issues to see if there's anything outstanding.

Feel free to leave the issue open until 0.7.0 is released.

**Comment by mc-meta** [comment]
Closing this long standing issue since proved to work properly with latest code.
