### ISSUE TITLE
Env SIGNALILO_ICINGA_KEEP_FOR has no effect.

### ISSUE THREAD

**Issue by Xavier-0965** [vshn/signalilo#51]
Hello,

thank you for this very good software.

We are using Signalilo Version v0.8.0 and want to remove 'normal' services after one day and not after 7 days.
The env variable `SIGNALILO_ICINGA_KEEP_FOR` is set with "24h".
But the services are not deleted.

In the log we can see, that the variable has been seend (see 3. message), but in the garbage collection, `keep_for`still has the default value: 168h.

```
Signalilo v0.8.0
Build time: 2020-11-11T10:02:48+00:00

{"level":"info","msg":"Configuring logger with LogLevel=2","time":"2021-01-15T17:05:49+01:00"}
{"level":"info","msg":"Signalilo UUID: signalilo-s01","time":"2021-01-15T17:05:49+01:00"}
{"level":"info","msg":"Keep for: 24h0m0s","time":"2021-01-15T17:05:49+01:00"}
{"level":"info","msg":"Starting heartbeat: interval 1m0s","time":"2021-01-15T17:05:49+01:00"}
[...]
{"level":"info","msg":"[Collect] Found service KubePodNotReady_77d3b5309c77cae4 with our bridge UUID","time":"2021-01-15T17:20:50+01:00"}
{"level":"debug","msg":"[Collect] Skipping service KubePodNotReady_77d3b5309c77cae4: keep_for = 168h0m0s; age = 160h37m39.407704s","time":"2021-01-15T17:20:50+01:00"}
[...]

Kind regards
Xavier
```

**Comment by simu** [comment]
Hi Xavier,

Please note that the value of `KEEP_FOR` is stored on each Icinga2 service object (as custom variable `keep_for`). Therefore, services which were created with 168h keep-for will only be garbage collected after those 168h.

Any services corresponding to alerts which are processed with your new Signalilo configuration will automatically have their `keep_for` value adjusted, but `keep_for` on services corresponding to resolved alerts is not updated when the Signalilo configuration changes.

Some local tests show that services which are created by Signalilo with `SIGNALILO_ICINGA_KEEP_FOR=1m` are correctly garbage-collected after being resolved for 1 minute.

Hope this helps & best regards,
-- Simon

**Comment by Xavier-0965** [comment]
Hi Simon,

thank you for the quick answer. Yes it helps a lot. I didn't understood, that the `keep_for` value is stored in the service objects.
So changing the value of `SIGNALILO_ICINGA_KEEP_FOR` has only an effect on the new services.

Kind regards
Xavier
