### ISSUE TITLE
CreateContainerError on openshift 4.5.35 | chdir to cwd /home/nonroot set in config.json failed: permission denied

### ISSUE THREAD

**Issue by vish-c** [vshn/signalilo#71]
Dear Signalilo Community,

We recently upgraded from Openshift 4.5.30 to 4.5.35 version and we have problems since then to get signalilo up and running. Also tested with the latest release signalilo:latest (b19ed615764c), with no success.

In the events, we see the following error 
`
Error: container create failed: time="2021-03-23T11:28:38Z" level=error msg="container_linux.go:348: starting container process caused \"chdir to cwd (\\\"/home/nonroot\\\") set in config.json failed: permission denied\"" container_linux.go:348: starting container process caused "chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"
`
Could it be that signalilo needs more configuration to make it work OR the issue could be on the OpenShift side ? 

Thank you in advance.

**Comment by srueg** [comment]
This is usually a permission error. You can try to set the pod's `.spec.containers.workingDir` to `/` in your deployment.

**Comment by mattttv** [comment]
hello. Thank you srueg for the tip. We had the same problem with openshift 4.6.21 (4.6.12 was working fine). We changed `.spec.containers.workingDir` inside the deployment of signalilo inside openshift-monitoring namespace to '/' and it worked.
Would be great if this would be fixed upstream inside helm charts? Thank you very much, Matt

**Comment by vish-c** [comment]
Hello @srueg Thank you very much for your prompt reply and the work around.  I can also confirm that it works after changing the workDir to /
