### ISSUE TITLE
Documentation about custom variables is incorrect

### ISSUE THREAD

**Issue by Xavier-0965** [vshn/signalilo#73]
Hello,

according to [custom variables](https://github.com/vshn/signalilo#custom-variables) I have defined a label named:
`icinga_emails_string`.

But in the Icinga service there is no custom variable `emails` but `label_icinga_emails_string`.

In the Log of signalilo I've found the following error:
~~~
{"level":"debug","msg":"Processing firing alert: alertname=UserPersistentVolumeFillingUp, severity=critical, message=Das PersistentVolume definiert durch test-4-xx im Namespace monitor-demo hat nur 0.006104% frei.","time":"2021-03-19T16:29:38+01:00"}
{"level":"info","msg":"Failed to map Icinga variable 'icinga_emails_string': unknown type","time":"2021-03-19T16:29:38+01:00"}
{"level":"info","msg":"creating service: UserPersistentVolumeFillingUp_b06ac30ea6e1f65b\n","time":"2021-03-19T16:29:38+01:00"}
{"level":"debug","msg":"Executing ProcessCheckResult on icinga2 for UserPersistentVolumeFillingUp_b06ac30ea6e1f65b: exit status 2","time":"2021-03-19T16:29:38+01:00"}
~~~

I have checked the [code](https://github.com/vshn/signalilo/blob/168bb49ecb2a516445f8a6542ed2b1503d51d4b3/webhook/variable_mapping.go#L45).
The label should be: `icinga_string_emails`.

I have changed it and it worked.

So, the documentation should be changed.

Kind regards
Xavier

**Comment by simu** [comment]
Hi Xavier,

Thanks for the report, I've updated the README to provide correct examples.

Best,
-- Simon

**Comment by Xavier-0965** [comment]
Hi Simon,

thank you very much for the fixing.

Kind regards
Xavier
