### ISSUE TITLE
Is it possible to map some other field  to plugin_output?

### ISSUE THREAD

**Issue by yoshi314** [vshn/signalilo#84]
I am using Grafana with alertmanager to forward alerts to icinga2 (because we have complex alerting logic, we don't want to do implement it twice).

The issue is that message from grafana goes into vars.label_message and i don't really receive anything on plugin_output. I could technically work that around in icinga2, but perhaps there's a way to do that in signalilo itself? 

Or maybe there is some alertmanager workaround.

**Comment by simu** [comment]
By default, Signalilo will use the value of annotation `message` on the incoming alerts to populate `plugin_output` of the Icinga2 service.

You can change this behavior by providing `--alertmanager_pluginoutput_annotations` (can be provided multiple times) to specify different annotations which contain the value that you want to use as `plugin_output` in the Icinga2 service.

Please note that currently there's no support in Signalilo to use the value of a label as the value for `plugin_output`.
