### ISSUE TITLE
Permission for icinga2 API user

### ISSUE THREAD

**Issue by dsch** [vshn/signalilo#94]
Which permissions are needed for the Icinga2 API user?
https://icinga.com/docs/icinga-2/latest/doc/12-icinga2-api/#icinga2-api-permissions

Currently we have granted all permissions to the user:
```
object ApiUser "signalilo" {
  permissions = [ "*" ]
}
```

**Comment by simu** [comment]
Hi,

I've updated the README to describe the required permissions for the API user if you implement the approach of having an Icinga service host and API user per Signalilo instance.
